### ISSUE TITLE
VS Code extension crashing

### ISSUE THREAD

**Issue by ahmednrana** [prominic/groovy-language-server#31]
Hi,

Previously, this extension has been working in VS Code but now I tried using it after several days and it is throwing this error

```
Aug 24, 2020 4:22:16 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.ast.ClassHelper.makeCached(ClassHelper.java:141)
	at org.codehaus.groovy.ast.ClassHelper.<clinit>(ClassHelper.java:77)
	at org.codehaus.groovy.classgen.Verifier.<clinit>(Verifier.java:133)
	at org.codehaus.groovy.control.CompilationUnit.<init>(CompilationUnit.java:169)
	at org.codehaus.groovy.control.CompilationUnit.<init>(CompilationUnit.java:138)
	at net.prominic.groovyls.compiler.control.GroovyLSCompilationUnit.<init>(GroovyLSCompilationUnit.java:43)
	at net.prominic.groovyls.config.CompilationUnitFactory.create(CompilationUnitFactory.java:70)
	at net.prominic.groovyls.GroovyServices.createOrUpdateCompilationUnit(GroovyServices.java:404)
	at net.prominic.groovyls.GroovyServices.setWorkspaceRoot(GroovyServices.java:121)
	at net.prominic.groovyls.GroovyLanguageServer.initialize(GroovyLanguageServer.java:70)
	... 16 more

[Error - 4:22:19 PM] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.ast.ClassHelper.makeCached(ClassHelper.java:141)
	at org.codehaus.groovy.ast.ClassHelper.<clinit>(ClassHelper.java:77)
	at org.codehaus.groovy.classgen.Verifier.<clinit>(Verifier.java:133)
	at org.codehaus.groovy.control.CompilationUnit.<init>(CompilationUnit.java:169)
	at org.codehaus.groovy.control.CompilationUnit.<init>(CompilationUnit.java:138)
	at net.prominic.groovyls.compiler.control.GroovyLSCompilationUnit.<init>(GroovyLSCompilationUnit.java:43)
	at net.prominic.groovyls.config.CompilationUnitFactory.create(CompilationUnitFactory.java:70)
	at net.prominic.groovyls.GroovyServices.createOrUpdateCompilationUnit(GroovyServices.java:404)
	at net.prominic.groovyls.GroovyServices.setWorkspaceRoot(GroovyServices.java:121)
	at net.prominic.groovyls.GroovyLanguageServer.initialize(GroovyLanguageServer.java:70)
	... 16 more

```

**Comment by joshtynjala** [comment]
I can confirm that the VSCode extension is working when I tested it today. One thing worth mentioning is that Java 8 or newer is required.

Based on this error text, I suspect that you are using Java 7 instead:

> java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
