### ISSUE TITLE
vs-code extension: Webpack build fails

### ISSUE THREAD

**Issue by TylerHaigh** [prominic/groovy-language-server#6]
Hey mate,
I had some difficulty getting the language server running in vs code this morning.
By the looks of things, the gradle file calls webpack to do the Typescript transpilation. On my machine, the webpack step was failing (but didn't fail the gradle build) which led to the extension not starting the language server.

I'm not familiar with webpack but this is the error I got from running webpack manually. Looks to be that it only happens when I run webpack with `-mode production`. Running webpack just by itself seems to work fine.

<details>
<summary>webpack production mode error</summary>

```
$ .\node_modules\.bin\webpack -mode production
C:\Github\groovy-language-server\vscode-extension\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
    at validateString (internal/validators.js:107:11)
    at Object.isAbsolute (path.js:350:5)
    at module.exports (C:\Github\groovy-language-server\vscode-extension\node_modules\webpack-cli\bin\utils\convert-argv.js:34:13)
    at C:\Github\groovy-language-server\vscode-extension\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Github\groovy-language-server\vscode-extension\node_modules\yargs\yargs.js:567:18)
    at C:\Github\groovy-language-server\vscode-extension\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Github\groovy-language-server\vscode-extension\node_modules\webpack-cli\bin\cli.js:365:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Github\groovy-language-server\vscode-extension\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

</details>

<details>
<summary>running webpack without mode flag</summary>

```
$ .\node_modules\.bin\webpack
Hash: 7834276068038cc0ad9f
Version: webpack 4.36.1
Time: 1655ms
Built at: 09/14/2019 10:08:59 AM
           Asset     Size  Chunks             Chunk Names
    extension.js  158 KiB       0  [emitted]  main
extension.js.map  632 KiB       0  [emitted]  main
Entrypoint main = extension.js extension.js.map
 [0] external "vscode" 42 bytes {0} [built]
 [7] external "path" 42 bytes {0} [built]
[11] external "fs" 42 bytes {0} [built]
[12] external "child_process" 42 bytes {0} [built]
[13] external "net" 42 bytes {0} [built]
[17] ./src/main/ts/extension.ts 5.85 KiB {0} [built]
[18] ./src/main/ts/utils/findJava.ts 2.4 KiB {0} [built]
[25] external "os" 42 bytes {0} [built]
[26] external "crypto" 42 bytes {0} [built]
    + 40 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
```

</details>

**Comment by joshtynjala** [comment]
I can reproduce your error by using `-mode`, but it works with `--mode` (notice that there are two hyphens).
